[package]
name = "emulator"
version = "0.1.0"
authors = ["Masterchef365 <duncan.freeman1@gmail.com>"]
edition = "2018"

[dependencies]
thiserror = "1"
anyhow = "1"
common = { path = "../common" }

[dev-dependencies]
assembler = { path = "../assembler" }
